# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CobraDemo < Formula
  desc ""
  homepage "https://github.com/LunaYin/homebrew-tools"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/LunaYin/cobra-demo/releases/download/v0.1.4/cobra-demo_0.1.4_Darwin_arm64.tar.gz"
      sha256 "80019eaa2e48f7c78616dfd5e10def71e0b15196af7ebf7193e411ee62187388"

      def install
        bin.install "cobra-demo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/LunaYin/cobra-demo/releases/download/v0.1.4/cobra-demo_0.1.4_Darwin_x86_64.tar.gz"
      sha256 "da81db7f31d66131b6e9fac5b7702136b28fa84d323000f7967835aea6dbb2ed"

      def install
        bin.install "cobra-demo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LunaYin/cobra-demo/releases/download/v0.1.4/cobra-demo_0.1.4_Linux_arm64.tar.gz"
      sha256 "11e85d0ce90537d28c9a45b1472ea96de6e69ef73cc452ccb6b58c7600a1a5df"

      def install
        bin.install "cobra-demo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/LunaYin/cobra-demo/releases/download/v0.1.4/cobra-demo_0.1.4_Linux_x86_64.tar.gz"
      sha256 "e382ad5c72580c543986784940af09f52213e3280c602dd596d400c204f74a74"

      def install
        bin.install "cobra-demo"
      end
    end
  end
end
